# Generated by Django 4.2.10 on 2024-04-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='DefaultCityValue', max_length=255)),
                ('checkinDate', models.DateField(blank=True, null=True)),
                ('checkoutDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
